FROM data_generation_v2:v2 

COPY . /workspace/robotwin_generation

RUN find /workspace/robotwin_generation -name "*.sh" -exec chmod +x {} \;

WORKDIR /workspace/robotwin_generation
ENTRYPOINT ["/workspace/robotwin_generation/entrypoint.sh"]